/*
 * Copyright (C) 2026 Lenik <autopch@bodz.net>
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif

#include "output.h"
#include "util.h"

#include <bas/base/str.h>
#include <bas/log/deflog.h>

#include <ctype.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int output_write_clusters(const pch_cluster_list *list, const include_index *ix) {
    for (size_t i = 0; i < list->count; i++) {
        const pch_cluster *c = &list->items[i];
        if (!c->path) {
            continue;
        }
        if (path_ensure_parent(c->path) != 0) {
            logerror_fmt("cannot create parent of %s: %s", c->path, strerror(errno));
            return -1;
        }
        FILE *fp = fopen(c->path, "w");
        if (!fp) {
            logerror_fmt("cannot write %s: %s", c->path, strerror(errno));
            return -1;
        }
        fprintf(fp, "/* Generated by autopch — do not edit by hand */\n");
        for (size_t h = 0; h < c->n_headers; h++) {
            const header_info *hi = g_hash_table_lookup(ix->headers, c->headers[h]);
            if (hi && hi->spell) {
                fprintf(fp, "#include %s\n", hi->spell);
            } else {
                fprintf(fp, "#include \"%s\"\n", c->headers[h]);
            }
        }
        if (fclose(fp) != 0) {
            logerror_fmt("error closing %s", c->path);
            return -1;
        }
        loginfo_fmt("wrote %s (%zu headers)", c->path, c->n_headers);
    }
    return 0;
}

typedef struct {
    const char *src;
    const char *cluster;
} map_entry;

static int cmp_map_entry(const void *a, const void *b) {
    const map_entry *ea = a;
    const map_entry *eb = b;
    return strcmp(ea->src, eb->src);
}

int output_write_map(const pch_cluster_list *list, const char *map_path) {
    if (!map_path) {
        return 0;
    }
    size_t n = 0;
    for (size_t i = 0; i < list->count; i++) {
        n += list->items[i].n_sources;
    }
    map_entry *entries = calloc(n ? n : 1, sizeof(*entries));
    if (!entries) {
        return -1;
    }
    size_t k = 0;
    for (size_t i = 0; i < list->count; i++) {
        const pch_cluster *c = &list->items[i];
        for (size_t s = 0; s < c->n_sources; s++) {
            entries[k].src = c->sources[s];
            entries[k].cluster = c->filename ? c->filename : "?";
            k++;
        }
    }
    qsort(entries, k, sizeof(*entries), cmp_map_entry);

    FILE *fp = fopen(map_path, "w");
    if (!fp) {
        free(entries);
        logerror_fmt("cannot write map %s: %s", map_path, strerror(errno));
        return -1;
    }
    for (size_t i = 0; i < k; i++) {
        fprintf(fp, "%s:%s\n", entries[i].src, entries[i].cluster);
    }
    free(entries);
    if (fclose(fp) != 0) {
        return -1;
    }
    loginfo_fmt("wrote map %s", map_path);
    return 0;
}

/* Match basename against PREFIX_BASE + digits + EXT */
static int is_pch_cluster_name(const char *name, const char *prefix_base, const char *ext) {
    if (!name || !prefix_base || !ext) {
        return 0;
    }
    size_t blen = strlen(prefix_base);
    size_t elen = strlen(ext);
    size_t nlen = strlen(name);
    if (nlen <= blen + elen) {
        return 0;
    }
    if (strncmp(name, prefix_base, blen) != 0) {
        return 0;
    }
    if (strcmp(name + nlen - elen, ext) != 0) {
        return 0;
    }
    const char *p = name + blen;
    const char *end = name + nlen - elen;
    if (p >= end) {
        return 0;
    }
    while (p < end) {
        if (!isdigit((unsigned char)*p)) {
            return 0;
        }
        p++;
    }
    return 1;
}

static const char *include_basename(const char *quoted_path) {
    const char *slash = strrchr(quoted_path, '/');
    return slash ? slash + 1 : quoted_path;
}

/* Parse a trimmed line as #include "..." / <...>; return 1 if matched.
 * *out_path points into line buffer (not owned). */
static int parse_include_line(char *line, char **out_path, int *angle) {
    char *p = line;
    while (*p && isspace((unsigned char)*p)) {
        p++;
    }
    if (strncmp(p, "#include", 8) != 0) {
        return 0;
    }
    p += 8;
    while (*p && isspace((unsigned char)*p)) {
        p++;
    }
    char open = *p;
    if (open != '"' && open != '<') {
        return 0;
    }
    *angle = (open == '<');
    p++;
    char *start = p;
    char close = *angle ? '>' : '"';
    while (*p && *p != close) {
        p++;
    }
    if (*p != close) {
        return 0;
    }
    *p = '\0';
    *out_path = start;
    return 1;
}

static int update_source_include(const char *path, const char *want_filename, const char *prefix_base,
                                 const char *ext) {
    FILE *in = fopen(path, "r");
    if (!in) {
        logerror_fmt("cannot read %s: %s", path, strerror(errno));
        return -1;
    }

    GPtrArray *lines = g_ptr_array_new_with_free_func(free);
    char *line = NULL;
    size_t cap = 0;
    long nread;
    int matched = 0; /* number of pch includes found */
    int replaced = 0;

    while ((nread = str_getline(&line, &cap, in)) > 0) {
        /* Keep original line text including newline if present */
        char *kept = xstrdup(line);
        if (!kept) {
            free(line);
            fclose(in);
            g_ptr_array_free(lines, TRUE);
            return -1;
        }

        char *work = xstrdup(line);
        if (!work) {
            free(kept);
            free(line);
            fclose(in);
            g_ptr_array_free(lines, TRUE);
            return -1;
        }
        chomp(work);
        char *inc_path = NULL;
        int angle = 0;
        int is_inc = parse_include_line(work, &inc_path, &angle);
        int is_ours = 0;
        if (is_inc && !angle) {
            is_ours = is_pch_cluster_name(include_basename(inc_path), prefix_base, ext);
        }
        free(work);

        if (is_ours) {
            matched++;
            if (!replaced) {
                int had_nl = (nread > 0 && line[nread - 1] == '\n');
                free(kept);
                if (asprintf(&kept, "#include \"%s\"%s", want_filename, had_nl ? "\n" : "") < 0) {
                    free(line);
                    fclose(in);
                    g_ptr_array_free(lines, TRUE);
                    return -1;
                }
                replaced = 1;
            } else {
                /* Drop duplicate pch includes from earlier runs */
                free(kept);
                continue;
            }
        }
        g_ptr_array_add(lines, kept);
    }
    free(line);
    fclose(in);

    if (!matched) {
        /* Insert at top */
        char *inc = NULL;
        if (asprintf(&inc, "#include \"%s\"\n", want_filename) < 0) {
            g_ptr_array_free(lines, TRUE);
            return -1;
        }
        g_ptr_array_insert(lines, 0, inc);
    }

    FILE *out = fopen(path, "w");
    if (!out) {
        g_ptr_array_free(lines, TRUE);
        logerror_fmt("cannot rewrite %s: %s", path, strerror(errno));
        return -1;
    }
    for (guint i = 0; i < lines->len; i++) {
        fputs((char *)lines->pdata[i], out);
    }
    g_ptr_array_free(lines, TRUE);
    if (fclose(out) != 0) {
        return -1;
    }
    loginfo_fmt("updated %s", path);
    return 0;
}

int output_write_sources(const pch_cluster_list *list, const char *prefix_base, const char *ext) {
    if (!prefix_base || !*prefix_base) {
        prefix_base = "cluster";
    }
    if (!ext) {
        ext = ".h";
    }
    for (size_t i = 0; i < list->count; i++) {
        const pch_cluster *c = &list->items[i];
        if (!c->filename) {
            continue;
        }
        for (size_t s = 0; s < c->n_sources; s++) {
            if (update_source_include(c->sources[s], c->filename, prefix_base, ext) != 0) {
                return -1;
            }
        }
    }
    return 0;
}
